### ISSUE TITLE
[Feature Request][Not issue] An introducing video about Markdown Table Editor

### ISSUE THREAD

**Issue by emisjerry** [ganesshkumar/obsidian-table-editor#10]
Hi, thanks for your Markdown Table Editor, it helps me a lot.

I've made a YouTube video which introduced this plugin in Chinese (English subtitle provided), maybe you will interested in: https://youtu.be/rZX_ZVPOgC8

**Comment by ganesshkumar** [comment]
Oh, that's awesome! Thanks @emisjerry. I shall link it in the README file

**Comment by ganesshkumar** [comment]
Added the link to your video in the README file
