### ISSUE TITLE
[BUG] Create a New Table - Version 0.1.2

### ISSUE THREAD

**Issue by FelipeRearden** [ganesshkumar/obsidian-table-editor#12]
**Describe the bug**
when creating a new table using the commands `Open Editor Below` and `Open Editor Next` the MTE window opens empty :(

**To Reproduce**
On an Active Note
1. Go to a empty line
2. Select one of the two commands : `Open Editor Below` or `Open Editor Next`
3. See error (images 1 and 2)

**Screenshots**
![50](https://user-images.githubusercontent.com/85180696/157498422-88c1cf33-4573-4438-9ee7-39ee9ecfe639.png)
![51](https://user-images.githubusercontent.com/85180696/157498424-bb186d9b-16c6-490b-ba27-d9d2fd178d6f.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version 0.1.1
 - Obsidian 0.13.23

**Additional context**
Sorry for bring problems @ganesshkumar !!!!

Let me know if you need more information

**Comment by FelipeRearden** [comment]
## Update from Version 0.1.2

This issue is not working prefect on version 0.1.2 !

Follow the same steps from before the MTE window is ready for the user input ....

There is only one new message box 



For me it's 100% okay but, as I said before, I think I should tell you about my experience with the new version and you decide the best path :)

Thank you very much !!!!!!!!!!!

**Comment by ganesshkumar** [comment]
@FelipeRearden , as of this what we are seeing in the v0.1.2 (where there are two rows with one column each) is the expected behavior. Let me know what kind of table you are expecting when you have the cursor on an empty line and opening MTE.

**Comment by FelipeRearden** [comment]
Hello @ganesshkumar !!!!

> @FelipeRearden , as of this what we are seeing in the v0.1.2 (where there are two rows with one column each) is the expected behavior. Let me know what kind of table you are expecting when you have the cursor on an empty line and opening MTE.

100% is okay !!! My only observation

**Comment by ganesshkumar** [comment]
I have pushed some changes into 0.3.0. Can you please check and let me know if this works for you?

**Comment by FelipeRearden** [comment]
> I have pushed some changes into 0.3.0. Can you please check and let me know if this works for you?


Hello again @ganesshkumar !!!!

I have two comments related to this FR from my tests on version `0.3.0`

## Settings 

Working perfect, this is the best solution :)

Now I can choose my standard table size. Thank you :)


## Bug

I think I found a Bug

With the caret cursor placed in the `Rows` or `Columns` field:

⏩ When we hit `backspace` to clear the field before type another number, we have this is input

![image](https://user-images.githubusercontent.com/85180696/167289813-a3c09bda-f681-49d9-a030-349dc68c6e6a.jpeg)

⏩ To be able to define a new number, I have to place the caret in the before the first letter `N` then hit 5 for example 

---

Let me know if you want me to create a new issue for this :)


Have a great day!
