### ISSUE TITLE
[Feature Request] Update current table

### ISSUE THREAD

**Issue by javiavid** [ganesshkumar/obsidian-table-editor#13]
**Is your feature request related to a problem? Please describe. **
I would like an option to update the current table.

**Describe the solution you'd like**
A button that when pressed deletes the current table from the document and pastes the new version.

**Comment by ganesshkumar** [comment]
Added in https://github.com/ganesshkumar/obsidian-table-editor/releases/tag/0.2.1 

Closing this!
