### ISSUE TITLE
[Feature Request] automatically escape pipes

### ISSUE THREAD

**Issue by Cammagno** [ganesshkumar/obsidian-table-editor#17]
Great plugin! :)

What about automatically escaping pipes whithin internal links when converting the table from MTE to markdown?

I mean, if in a cell of Markdown Table Editor I write something as [[LinkedNote|Title of the Link]]
it could convert it into
|   [[LinkedNote\\|Title of the Link]]   |
instead of 
|   [[LinkedNote|Title of the Link]]   | as it does now.

Of course if the text inserted in the cell is already "pipe-escaped"
[[LinkedNote\\|Title of the Link]]
it should leave it as it is.

In this way, it will avoid to break the table if the user forget to escape a pipe in a link, and it will allow to directly past in the cells the links without need to escape all of them.

**Comment by ganesshkumar** [comment]
With v0.2.2 this is fixed
