### ISSUE TITLE
[BUG]: Table not readable in Dark mode

### ISSUE THREAD

**Issue by chrisgrieser** [ganesshkumar/obsidian-table-editor#2]
Great plugin! I just uninstalled Tableflip after trying this one out :)

**Describe the bug**
The pane is not readable in Dark Mode. Happens in the default theme, so it's not a theme issue.
<img width="1018" alt="Screenshot 2022-02-26 22 22 54" src="https://user-images.githubusercontent.com/73286100/155859575-1ef1aeed-9187-4d50-a842-4c2e04d16af5.png">

**To Reproduce**
switch to dark mode

**Expected behavior**
better styling, grey is too light and the white on gray not readable

**Comment by chenxin0397** [comment]
Some words are not clear under the dark theme of blue topaz
Please consider tweaking the CSS styles

**Comment by psychsatani** [comment]
Yeah I have the same issue with unreadable headers only in dark mode and this is there with all themes, including default. It looks beautiful in light mode but I dont use it.

**Comment by ganesshkumar** [comment]
Fixed the issue and made a new release (0.1.1). 

Also, the plugin is available in the community plugin list. You can download it from there directly 🎉  
I have checked the fix in few dark themes. Let me know if you face any issue.

**Comment by FelipeRearden** [comment]
Working perfect on Version 0.1.1 - Obsidian 0.13.23 - Dark and Light Original Obsidian Theme
