### ISSUE TITLE
[Feature Request] Option to choose where to open MTE

### ISSUE THREAD

**Issue by Cammagno** [ganesshkumar/obsidian-table-editor#20]
I know that we can set hotkeys for different locations for the MTE (under, right, floating), but I'd like an option to set where to open it when clickiung on the icon in the left sidebar.

Also, the MTE commands are not available in the Command Palette (at least for me), they only works by hotkey.

**Comment by ganesshkumar** [comment]
Until I add settings pane, can you right click on the icon to open the menu and choose the direction where you want to open the editor?

**Comment by ganesshkumar** [comment]
Similar issue #24

**Comment by Cammagno** [comment]
> Until I add settings pane, can you right click on the icon to open the menu and choose the direction where you want to open the editor?

Oh, good, thanks!

**Comment by ganesshkumar** [comment]
I have pushed some changes into 0.3.0. Can you please check and let me know if this works for you?  
You can set this direction from the settings (default direction)

**Comment by Cammagno** [comment]
> I have pushed some changes into 0.3.0. Can you please check and let me know if this works for you? You can set this direction from the settings (default direction)

it works, thanks! :)
