### ISSUE TITLE
[BUG] {iPadOS} Copy/Paste Hotkey not working inside a cell

### ISSUE THREAD

**Issue by FelipeRearden** [ganesshkumar/obsidian-table-editor#21]
Hello @ganesshkumar 👋

**Describe the bug**
This bug only appears on iOS.

The Commands `Copy` and `Paste` from Obsidian   inside a cell does not work on Mobile  😢 

On Desktop is working perfect !

🔭 it’s important to address that using the iOS built in popover is working !

![28DA865B-BCEA-489C-8D78-EC5925C517D1](https://user-images.githubusercontent.com/85180696/161398378-9d096721-87ba-478c-bdb1-7bfc64383a7d.jpeg)

**To Reproduce**
1- Copy something to clipboard
2- Edit a table or create a new table
3- Inside a cell hit `Cmd+C` or `Cmd+V`  

**Expected behavior**
Use the clipboard content inside a cell

**Screenshots**

**Smartphone (please complete the following information):**
 - Device:  iPad Pro
 - OS: iOS15.4
 - Version 0.2.1

**Additional context**

If is not possible to support Copy and Paste via hotkey, my suggestion would be to add COPY, CUT and PASTE to the spectacular operations menu :)

![82974BD5-1567-47F3-8CFC-27B739F28679](https://user-images.githubusercontent.com/85180696/161398039-f5de1206-922a-4231-a39a-a4b2826591a7.jpeg)

---

Thanks for reading this !!!!

Have  a great day !!!! 🌞

**Comment by ganesshkumar** [comment]
I have pushed some changes into 0.3.0. Can you please check and let me know if this works for you?

**Comment by FelipeRearden** [comment]
> I have pushed some changes into 0.3.0. Can you please check and let me know if this works for you?

Hello @ganesshkumar !!!!

Sorry for my late reply, thank you very much !

It's working perfect on version `0.3.0` on Obsidian `0.14.6` on **Desktop** and on **Mobile** {iPadOS}


Have a great day!
