### ISSUE TITLE
Feature Request: Open in Hover Editor

### ISSUE THREAD

**Issue by chrisgrieser** [ganesshkumar/obsidian-table-editor#22]
Being able to open the table view in the [hover editor](https://obsidian.md/plugins?id=obsidian-hover-editor) would make this plugin really great!

similar to this
https://discord.com/channels/686053708261228577/855181471643861002/961957079952789515

**Comment by FelipeRearden** [comment]
Hello @chrisgrieser !!!

Sorry to step into your FR :) Just trying to help 

Don't you have this command in you Command Palette ?
![q1](https://user-images.githubusercontent.com/85180696/163453899-0dce97d0-ca3c-4b0e-805c-7e951cb07171.png)

---

Have a great day!

**Comment by chrisgrieser** [comment]
um, didn't know that there was this command lol 😆 
thx!

**Comment by FelipeRearden** [comment]
> um, didn't know that there was this command lol 😆 
> 
> thx!

💙
