### ISSUE TITLE
[Feature Request] Remember location to open

### ISSUE THREAD

**Issue by ndharari** [ganesshkumar/obsidian-table-editor#24]
I'd like the window to always open bellow. Now, the default setting is that when I click the button it opens in the side. This is kinda bothersome when I'm using Sliding Panes.

**Comment by ganesshkumar** [comment]
@ndharari, are you mentioning about the button on the left ribbon?

**Comment by ndharari** [comment]
Yes! I would like that when I click it the plugin always opens below.
If it's not too much problem 😄

**Comment by ganesshkumar** [comment]
Until I add settings pane, can you right click on the icon to open the menu and choose the direction where you want to open the editor?

**Comment by ganesshkumar** [comment]
I have pushed some changes into 0.3.0. Can you please check and let me know if this works for you?
You can set this direction from the settings (default direction)

**Comment by ndharari** [comment]
works perfectly. thanks!
