### ISSUE TITLE
[BUG]Update table button seems buggy 

### ISSUE THREAD

**Issue by jiewangjs** [ganesshkumar/obsidian-table-editor#25]
When the update table button clicked, it flushes out all the contexts of the current note, leaving only the table.

**Comment by ganesshkumar** [comment]
@jiewangjs, which version are you using?

**Comment by jiewangjs** [comment]
latest. i install it freshed a few days ago.



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Ganessh ***@***.***> |
| 日期 | 2022年05月02日 09:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ganesshkumar/obsidian-table-editor] [BUG]Update table button seems buggy (Issue #25) |

@jiewangjs, which version are you using?

**Comment by emisjerry** [comment]
If there's no line breaks between header and table, after updating table, the `## 10. Headings` will be lost.

```
## 10. Headings
| Left aligned text | Centered text |  Right aligned text |
|:------------------|:--------------|:--------------------|
| Cell1             | Cell1         | Cell1               |
| Cell2             | Cell2         | Cell2               |
| Cell3             | Cell3         | Cell3               |  
```
![image](https://user-images.githubusercontent.com/131511/166859116-5c3d63ab-59c2-42d3-99a3-276274e96113.png)

**Comment by ganesshkumar** [comment]
Needs to support no line breaks before the table.

**Comment by ganesshkumar** [comment]
Can you check and confirm this in the latest version?

**Comment by hihihlo** [comment]
about "Update Table" button, **_this bug still exist_**. (my version is 0.3.1)

case 1: as @emisjerry said, the Headings will be lost.
case 2: I use custom Q/A format within plugin "Obsidian-to-Anki",
it mark Answer("A:") end by empty line, so I can't add empty line before/after table.
below is a valid Q/A pair 
```
Q: this is a test question
A:    
some prefix description
| hdr-1 | hdr-2 |
|:----- |:----- |
| aa1   | aa2   |
| bb1   | bb2    |
- some postfix description
```
**_if I press "Update Table" button, every thing disappear except markdown table !_**

is it possible to fix the bug ?

**Comment by RedLilith** [comment]
I just tried updating a table in one of my notes leaving a 3 empty spaces above it, and all of my note still disappeared. My obsidian version: 1.3.5, plugin version: 0.3.1, on Win 11 OS
