### ISSUE TITLE
[Feature Request] Support for embedded table in callouts

### ISSUE THREAD

**Issue by cumany** [ganesshkumar/obsidian-table-editor#27]
For example, the following two types of callouts are written
The obsidain-table-editor plugin cannot render:
```
> [!NOTE]
> | title | content |
 | ----- | ------- |
 | 1111      |    333     |
```
or
```
> [!NOTE]
> | title | content |
>  | ----- | ------- |
> | 1111      |    333     |
```

**Comment by ganesshkumar** [comment]
This is interesting! I wasn't aware of the fact that callouts can support tables

**Comment by ganesshkumar** [comment]
Can you check and confirm this in the latest version?

**Comment by cumany** [comment]
Thank you very much It seems to be working very well 
But I found a little bug, if there is a blank row after the table, every time I update the table, a new blank row will be added
eg：
```
> [!NOTE]          
|  1111  |  222   |
|:-------|:-------|
|   5555 |  5555  |  


```

**Comment by ganesshkumar** [comment]
I have created a separate issue for the new line issue. Will fix it over the next weekend!
