### ISSUE TITLE
[BUG] Need to change the hot key for cell menu

### ISSUE THREAD

**Issue by ganesshkumar** [ganesshkumar/obsidian-table-editor#28]
**Describe the bug**
[Need to change the hot key for cell menu](https://github.com/ganesshkumar/obsidian-table-editor/issues/4#issuecomment-1063986069)

**Comment by ganesshkumar** [comment]
Can you check and confirm this in the latest version?

**Comment by FelipeRearden** [comment]
Hello @ganesshkumar !!!

Thank you very much for the fix!!!!

Working perfect on version `0.2.3` on Obsidian Mobile - iPadOS 15.4


Have a great day!!!!
