### ISSUE TITLE
[BUG] CSV to Editor failed

### ISSUE THREAD

**Issue by emisjerry** [ganesshkumar/obsidian-table-editor#29]
My simple CSV content:

```
111,222,333
444,555,666
777,888,999
```

Select these lines, invoke Table Editor. It responsed:

![image](https://user-images.githubusercontent.com/131511/166659275-8b8c309b-1e32-4885-8a67-2756df753e24.png)

Obsidian: v0.14.9
Table Editor: latest version

**Comment by ganesshkumar** [comment]
Looks like only '|' delimiter is getting parsed in the latest version. Will fix it

**Comment by ganesshkumar** [comment]
Can you check and confirm this in the latest version?

**Comment by emisjerry** [comment]
It's OK now. Thanks.
