### ISSUE TITLE
[Feature Request] Caret Cursor Focused on the  `Rows:` filed

### ISSUE THREAD

**Issue by FelipeRearden** [ganesshkumar/obsidian-table-editor#3]
**Is your feature request related to a problem? Please describe. **
Hello @ganesshkumar !!!!!

When using the command to Open Md Table Editor Window, would be amazing if the caret cursor is fosused in the first text field `Rows:`.

This way I could just start to create/edit my table using only the keyboard !!!!!!
- Since I can use TAB to navigate between the fields in the window :)

**Describe alternatives you've considered**
None

**Additional context**
Not this time.

Thank you very much for creating this. It´s a plugin that I wanted in Obsidian for a long time. Now I can finally create/edit tables without effort :)

I wish you a fantastic day!!!!!

**Comment by ganesshkumar** [comment]
Thanks for the feedback. Actually, I didn't think of this.

Does it make sense to skip the header and set the focus on the first data row?
- It looks reasonable to me when the user selects some content and open the table editor with some initial content.
- While creating a new table from scratch, it looks little weird to see two empty cells with the carot on the second one (first data row)

Let me know your thoughts on this.

**Comment by FelipeRearden** [comment]
Hello @ganesshkumar !!!!

Thanks your reply !!!! 

I agree with you and I think we have 2 different approaches based new table and edit table

**Approach 1: New Table**
For new tables, I think we could start at `.button-container.mte>input` (Rows :) because the first decision that the user have to do is the size (rows and columns) of the table

**Approach 2: Edit Table**
For Edit tables, I think we could start at `.mte.cell-container.relative.data` as you said because most of the time we are looking for editing the content and not the header 

---

If it was not possible to identify New Table from Edit Table (maybe if nothing is selected means New Table?) I think we should start at `.button-container.mte>input` (Rows :) because I think the most common workflow will be creating new tables instead editing tables :)

---

Thanks for letting me share with you my thoughts !!!!!

Have a great day!

**Comment by ganesshkumar** [comment]
Fixed the issue and made a new release (0.1.1).  
Also, the plugin is available in the community plugin list. You can download it from there directly 🎉

**Comment by FelipeRearden** [comment]
Working Perfect on version 0.1.2 both for new table and for edit table.

Thank you very much !!!!!!!!
