### ISSUE TITLE
[Feature Request] New Command: Open Editor (Horizontally)

### ISSUE THREAD

**Issue by FelipeRearden** [ganesshkumar/obsidian-table-editor#5]
**Is your feature request related to a problem? Please describe. **
Many times we have 3 or 4 notes open in a tiny screen laptop and open a new window vertically make a little bit difficult to create a table (image 1) :) 

**Describe the solution you'd like**
Would be amazing if we have a command that open the Md Table Editor Horizontally (image 2).

**Additional context**
![30](https://user-images.githubusercontent.com/85180696/155882494-81a22a2d-1b23-4958-a5fa-ab0d92b90127.png)

![31](https://user-images.githubusercontent.com/85180696/155882501-a2aad4d7-31eb-4fd3-bfd4-01325bba32f2.png)

**Comment by ganesshkumar** [comment]
Right clicking on the ribbon icon (left click open it on the right side by default)
![image](https://user-images.githubusercontent.com/2135089/157423537-aea8d317-3a92-406d-9257-d1ba8a7f4fec.png)

From command palette
![image](https://user-images.githubusercontent.com/2135089/157423718-2969a0d8-c0d6-485c-bc9c-14ed4883daa6.png)

**Comment by ganesshkumar** [comment]
Fixed the issue in 0.1.1. Let me know if you face any issue!

**Comment by FelipeRearden** [comment]
> Fixed the issue in 0.1.1. Let me know if you face any issue!

Working Perfect on version 0.1.2 both for new table and for edit table.

Thank you very much !!!!!!!!
