### ISSUE TITLE
[Feature Request] Can the icons on the menu refer to the "Advanced Tables" plugin? This makes it more intuitive

### ISSUE THREAD

**Issue by ganesshkumar** [ganesshkumar/obsidian-table-editor#7]
**Is your feature request related to a problem? Please describe.**
From (https://github.com/ganesshkumar/obsidian-table-editor/issues/4#issuecomment-1053564868)

**Additional context**
https://user-images.githubusercontent.com/73974352/155885500-729feb72-da23-412f-8b49-5840c91497d2.png

**Comment by ganesshkumar** [comment]
![image](https://user-images.githubusercontent.com/2135089/157433613-932cf13a-8f2e-45b7-bc05-e1f96c2a15c4.png)

Using the same icon for add row above and add row below. Similarly for add column left and add column right. Will fix it when I come across better svgs which can visually separate them.

**Comment by ganesshkumar** [comment]
Added in 0.1.1

**Comment by FelipeRearden** [comment]
Working perfect on Version 0.1.1 - Obsidian 0.13.23

Thank you very much for this feature!!!!!
