### ISSUE TITLE
[Feature Request] New Command: Select  Markdown Table

### ISSUE THREAD

**Issue by FelipeRearden** [ganesshkumar/obsidian-table-editor#8]
**Is your feature request related to a problem? Please describe. **
Since the starting point to edit tables is to make a selection of the markdown table in the note, I think would be amazing if we have a new command that selects a table based on the position of the caret cursors.

**Describe the solution you'd like**
If the caret cursor is placed inside a markdown table, hitting the new command will select the entire table ! 

--- 

Thanks for reading this! 

Have a great day!!!!

**Comment by ganesshkumar** [comment]
@FelipeRearden , does this work?

![expand to select table](https://user-images.githubusercontent.com/2135089/157458161-d6c77c35-fa62-4d39-a2dc-049e950047b2.gif)

Binding it to the same command. Logic used

```
if there is a selection
    user selected text is used as input
else
    explore on either side of the cursor for empty line
    all the lines between this will be used as input
```

**Comment by FelipeRearden** [comment]
> @FelipeRearden , does this work?
> 
> 
> 
> ![expand to select table](https://user-images.githubusercontent.com/2135089/157458161-d6c77c35-fa62-4d39-a2dc-049e950047b2.gif)
> 
> 
> 
> Binding it to the same command. Logic used
> 

Forgive for my comment @ganesshkumar , let me share why I think we need to select the table as well. 

Following your video, after entering in the md table editor window the next steps for the user are:
- Step 1: Hit copy to markdown button
- Step 2: Paste the new table to overwrite the previous table (update). 

This way, if we already have the table selected, I don't need to manually select the table than hit CRTL+V :)

Let me know what you think :)

Have a great day !!!!

**Comment by ganesshkumar** [comment]
![select table](https://user-images.githubusercontent.com/2135089/157481112-2beb7b5f-ec1a-49a0-af56-6c16da392abd.gif)

**Comment by ganesshkumar** [comment]
Happy to help :) Thank you for the valuable feature suggestions!

**Comment by FelipeRearden** [comment]
> Happy to help :) Thank you for the valuable feature suggestions!

Thank you very much @ganesshkumar !!!!!!!!!!!!!!!

**Comment by FelipeRearden** [comment]
I already installed version 0.1.1 and I think I found a bug ....

Take a look at the images ... when selecting a table with the new command, the line before the first row is being selected two    
- in my example my table in the middle of the note (not in line 1)
![50](https://user-images.githubusercontent.com/85180696/157495198-44d513d4-aa6e-47c3-a52c-229ebe066744.png)

With or without content

![51](https://user-images.githubusercontent.com/85180696/157495403-9a717792-c96b-4c34-806d-2c8c42024c5d.png)

Fun Fact -> sometimes is working prefect .... :)

![52](https://user-images.githubusercontent.com/85180696/157495661-7f577e70-5ee0-4ba0-885a-468c2cefc640.png)

I was trying to investigate if is something related to the caret cursor position when I am hitting the command ...

But I did not found a pattern to share with you :)

I hope you can reproduce this on your end  :pray:

**Comment by ganesshkumar** [comment]
Damn! Some regression happened. I should add some tests before adding more functionality!

**Comment by ganesshkumar** [comment]
I checked for the same from my end.

1. When you put your cursor on the first line of the table (header) and invoke the function, do you see extra selection on top line?
2. Similarly, when you put your cursor on the last line of the table and invoke the function, do you see extra selection on bottom line?

**Comment by ganesshkumar** [comment]
@FelipeRearden Can you update it once again? 0.1.2 - I have included some fixes for both the issues. Works for my, let's see if it fixes the issues for you as well.

**Comment by FelipeRearden** [comment]
> @FelipeRearden Can you update it once again? 0.1.2 - I have included some fixes for both the issues. Works for my, let's see if it fixes the issues for you as well.

Sure !!!! I'm here :)

Just to let you know about version `0.1.2` the manifest.json from this release is version `0.1.1`. This way I can't see an update button on Obsidian. 

Just to check with you if I can change manually the manifest.json from the 0.1.2 release and start my test ?

**Comment by FelipeRearden** [comment]
> 1. When you put your cursor on the first line of the table (header) and invoke the function, do you see extra selection on top line?

Working perfect on version `0.1.2` !!!!! Thank you very much @ganesshkumar for your help !!!!!!

 
> 2. Similarly, when you put your cursor on the last line of the table and invoke the function, do you see extra selection on bottom line?

Working perfect on version `0.1.2` !!!!! Thank you very much @ganesshkumar for your help !!!!!!

---

Let me just add one little information to see if you want make some changes or not ...

When we have some text in the line AFTER the last line of the table, we have a little issue. Take a look ...

![image](https://user-images.githubusercontent.com/85180696/157516856-34850dbd-9d1f-4bbd-bb4c-4bbb5b67ecf8.jpeg)

![image](https://user-images.githubusercontent.com/85180696/157516877-6395dbe0-1f4b-4372-a3f9-312c579c88e7.jpeg)

I'm pointing this to you because it's very common to use some tag like `small` after the table to add some explanation about the table like a footnote 

For me it's okay on version `0.1.2` but as a tester, I think is my duty to present to you all my findings :)

Thanks for the quick reply :)

**Comment by FelipeRearden** [comment]
Hello @ganesshkumar !!!!

Sorry to bother you :)

One more information about selecting a table when you have content in the next line of the table ... https://github.com/ganesshkumar/obsidian-table-editor/issues/8#issuecomment-1063282689

The amazing plugin [Obsidian Charts](https://github.com/phibr0/obsidian-charts) has a new feature that let´s you create Charts from Tables !!!!!

If you look at he documentation, you will see that it uses a `table-id` in the next line after the table 
- https://charts.phibr0.de/Chart%20from%20Table#link-table-to-chart

This way, would be amazing if we avoid this line when selecting a markdown table :pray:

---

Thanks for reading this and have a great day!!!!!!!!!

**Comment by ganesshkumar** [comment]
With v0.2.2, this is fixed

**Comment by FelipeRearden** [comment]
Hello @ganesshkumar !!!!

Thank you very much for the fix 💙

Working perfect on version `0.2.2` Obsidian `0.14.6` and Obsidian Mobile 

One ask :)

When you have some time, would you mind taking a look at these two issue 🙏 

- [A comment from Issue 4 on iPadOS](https://github.com/ganesshkumar/obsidian-table-editor/issues/4#issuecomment-1063986069)

- #18

Thank you very much and have a great day 🌞

**Comment by ganesshkumar** [comment]
Sure @FelipeRearden, I have triaged the feature requests. Will implement them soon!
