### ISSUE TITLE
[BUG] "\" Is not processed

### ISSUE THREAD

**Issue by shunnkou** [ganesshkumar/obsidian-table-editor#9]
**Describe the bug**
When using \ to use a link alias, the "`\`" doesn't get processed and the link gets split to two columns.

**To Reproduce**
1. In a table, `[[enter a link\|with an alias]]`
2. Open the markdown table editor
3. Two columns show up, split at |

**Expected behavior**
There should be only 1 column, with the alias displayed properly.

**Screenshots**
Error/multiple columns:
![image](https://user-images.githubusercontent.com/50721364/156279274-13f79725-259d-484f-b27a-4cc4c3d97c17.png)

What it normally looks like:
![image](https://user-images.githubusercontent.com/50721364/156279392-5658c74a-16e5-4b3b-8d78-047e08300fb4.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by ganesshkumar** [comment]
Does this also happen in the markdown editor as well?

I have a table as follows

![image](https://user-images.githubusercontent.com/2135089/157459843-e8cb7717-a0e6-4de6-be44-c48d1eef382a.png)

If I go to view mode, the column is broken exactly like how it happens in the plugin's editor.

![image](https://user-images.githubusercontent.com/2135089/157459930-02742d2f-6df3-4c13-bce1-c86740e8f55f.png)

**Comment by ganesshkumar** [comment]
Same in GitHub markdown preview mode as well

![image](https://user-images.githubusercontent.com/2135089/157460115-5554a0ed-f5d4-4446-a015-26742b67960c.png)

So, it looks like we are honoring the general markdown parsing logic.  Fixing it in the plugin alone will solve the issue?

**Comment by ganesshkumar** [comment]
This is the state of the latest code. Looks good?
![wikilink in markdown table](https://user-images.githubusercontent.com/2135089/157475560-d681f2de-73b9-42ab-bc85-27a952f9e49e.gif)

**Comment by FelipeRearden** [comment]
> Don't be sorry! Your input is really helpful :) 

Thank you very much @ganesshkumar I'm happy to know my comment helped !!!!!!!

**Comment by ganesshkumar** [comment]
@shunnkou. I have fixed the issue and made a new release (0.1.1).  Also, the plugin is available in the community plugin list. You can download it from there directly 🎉
